### ISSUE TITLE
Go error

### ISSUE THREAD

**Issue by Shark-Linux** [lxc/lxd-demo-server#10]
Just a heads up that starting today builds of the demo server started to fail for me. The error given matches the one referenced in [Errors in rest.go #4 ](https://github.com/lxc/lxd-demo-server/issues/4)
Anything I can be doing to help myself ?

**Comment by Shark-Linux** [comment]
./rest.go:366: not enough arguments in call to lxdDaemon.LocalCopy

**Comment by brauner** [comment]
Ah yeah, likely the client needs to be updated against master since some client functions gained additional arguments.

**Comment by Shark-Linux** [comment]
Aha. I thought something was up when i had multiple mentions of it in my inbox. The demo is included as a sandbox tool in Shark Distro. I have an installer release going out today so Im gonna axe it for now and look at it for re-inclusion on the next ISO build

**Comment by brauner** [comment]
@Shark-Linux, not that client api breaks will be way less frequent once @stgraber's client rewrite lands. This will enable us to give a lot stronger client api guarantees. :)

**Comment by stgraber** [comment]
Fixed, and yeah, as soon as I land the first pass on the new client library, I'll port lxd-demo-server over to it which should make things much more stable going forward :)

**Comment by Shark-Linux** [comment]
Devine Intervention!

Best of luck with the new client, Ill keep an eye out for updates.
Cheers,
