### ISSUE TITLE
Cannot create container

### ISSUE THREAD

**Issue by Shark-Linux** [lxc/lxd-demo-server#12]
#11 Is pretty much an exact description of my issue, only a local build and not the demo server hosted on the website. Same build script always worked in the past so Im not sure the best place to start in determining the cause. Any suggestions?

**Comment by stgraber** [comment]
Look at the output of lxd-demo-server or the lxd log

**Comment by Shark-Linux** [comment]
I'm sorry I meant to update but got sidetracked. I was able to run it successfully after going back to lxd 2.13 from 2.15 (2.14 had been skipped for unrelated issue) Furthermore, once it was up and running and I upgraded back to 2.15 it continued to work. Ive made the 2.13 the default in SharkLinux and the newest version is done via opt-in upgrade (with a notice to build the server first if its wanted on the system) Not my ideal solution but unfortunately too many pressing things right now to give this priority. I read somewhere about a change to the lxd client.. any chance thats a factor?

**Comment by stgraber** [comment]
Nope, lxd-demo-server directly talks to the API, it doesn't use the command line client.

**Comment by Shark-Linux** [comment]
It is consistent anyway, in the same vm setting and install/build script  2.13 passed 5/5 and 2.15 went 0/5. Upgrading lxd afterwards didnt cause any harm. ill have to dig a bit when I have a chance and look a bit closer. Go ahead and close if you'd like

**Comment by stgraber** [comment]
I can't seem to reproduce your problem:
```
root@lantea:~# snap install lxd
lxd 2.15 from 'canonical' installed
root@lantea:~# lxd init
Do you want to configure a new storage pool (yes/no) [default=yes]? 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (dir, btrfs, zfs) [default=zfs]: 
Create a new ZFS pool (yes/no) [default=yes]? 
Would you like to use an existing block device (yes/no) [default=no]? 
Size in GB of the new loop device (1GB minimum) [default=21GB]: 
Would you like LXD to be available over the network (yes/no) [default=no]? 
Would you like stale cached images to be updated automatically (yes/no) [default=yes]? 
Would you like to create a new network bridge (yes/no) [default=yes]? 
What should the new bridge be called [default=lxdbr0]? 
What IPv4 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]? 
What IPv6 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]? 
LXD has been successfully configured.
root@lantea:~# snap install lxd-demo-server
lxd-demo-server git from 'stgraber' installed
root@lantea:~# snap connect lxd-demo-server:lxd lxd:lxd
lxd-demo-server git from 'stgraber' installed
```

I could then hit http://IP:8080 and get a working session.

**Comment by Shark-Linux** [comment]
Yea, you wouldnt. Doing the old method by building with go.

**Comment by stgraber** [comment]
Ok, closing this for now as there's nothing obviously wrong with LXD or the demo server that I can work on fixing. If you can reproduce this, please attach the output of lxd-demo-server and the LXD log, one of the two should give more details on what's failing.
