### ISSUE TITLE
Stuck on: Starting the container...

### ISSUE THREAD

**Issue by raymov** [lxc/lxd-demo-server#13]
Have tried both latest versions of Chrome & Firefox:
https://linuxcontainers.org/lxd/try-it/
After accepting terms, page shows:

Server status (green)
You are connected over: IPv4 (220.x.x.251)
The demo server is currently running 5 user sessions out of 32

Starting the container...
(Throbber animation spins, but nothing happens)

**Comment by stgraber** [comment]
Looks like it's working again. The server auto-rebooted a few hours ago so I guess that fixed that...
