### ISSUE TITLE
After some time running the container not start.

### ISSUE THREAD

**Issue by condector** [lxc/lxd-demo-server#18]
I saw a similar question but running on your own server. Here, my `lxd-demo-server` is running and create normally the container when the "rules" were accepted. 

But, if I not create any container for some hours and try to create a new one, the server creates the container itself (but it remains stopped), but the container was not started, so the interface did not open the terminal.

Not saw any logs on the terminal on the running `lxd-demo-server` process.

I think that, probably, some process was not starting the container after that change related to the alias container image.

If I kill the `lxd-demo-server` process, it start to create and remove the containers again, but keep one container on _stopped_ state and I need to remove it manually.

Only to clarify, I create this environment here to allow my computer science students to _play_ with Linux. Thanks a lot for LXD/LXD-demo-server environment created.

**Comment by condector** [comment]
I installed the lxd from snap:

`Client version: 3.8`
`Server version: 3.8`

And, because `lxd-demo-server` not have the Unix socket path to the LXD, I create a symbolic link to fulfill that:

`lrwxrwxrwx 1 root root 36 dez 20 08:46 /var/lib/lxd/unix.socket -> /var/snap/lxd/common/lxd/unix.socket`

The `lxd-demo-server` create the container, but not start it... but when I kill it and run the server again, it start to work normally for a while.

**Comment by condector** [comment]
I will close it because I imagine that you have a lot of problems to solve other things (much more important). Just remember that this problem is occurring.

**Comment by stgraber** [comment]
No point in closing an issue that hasn't been resolved

**Comment by condector** [comment]
Ok, no problem. Thanks.

**Comment by stgraber** [comment]
I've been trying to replicate this issue by restarting LXD, making it crash, ... with no success.

The snap is a bit outdated though so I'll at least refresh it to use a newer build of the client but if there's a particular case where the event handling gets into a bad state as the above suggests, I've not yet found a way to replicate it.

**Comment by condector** [comment]
@stgraber do the test here in another situation.

I copy the build `lxd-server-demo` from my old server to a new one installed from scratch (Ubuntu 18.04 LTS). Not use `btrfs` as disk, only use `dir` this time, and the issue has not appeared again. Maybe something related to the go become unstable on the other server.

Now I will close the "bug" because the problem was in my old environment. I'm testing the new one and the problem does not occur again.
