### ISSUE TITLE
Change term.js to xterm.js

### ISSUE THREAD

**Issue by nutterthanos** [lxc/lxd-demo-server#19]
The lxd-demo-server still uses a non maintained fork of xterm.js
https://github.com/chjj/term.js

**Comment by stgraber** [comment]
I don't mind switching to something else but it's not a simple drop in replacement and I don't have time to spend the number of hours needed for a switch which at best nobody would notice and at worse would cause some regressions.

If you care and have the time then send a pull request and with sufficient testing, we can switch over to it.

**Comment by nutterthanos** [comment]
Yeah but an update to any web could break the JavaScript code of term.js

**Comment by nutterthanos** [comment]
Also one more thing it’s that I can’t copy any text from the terminal window on mobile but paste works.

**Comment by nutterthanos** [comment]
Anyway its just a demo so no point then
Closing Issue.
