### ISSUE TITLE
How to launch multiple demo server ? 

### ISSUE THREAD

**Issue by Lakshmipathi** [lxc/lxd-demo-server#21]
Hi,
 
I'm exploring replacement for Docker environment for webminal.org and found this project.

Followed these steps https://ubuntu.com/blog/run-your-own-lxd-demo-server and accessed demo server locally. As a LXD newbie, I'm not sure whether its possible to setup multiple `lxd-demo-server` on a host. I guess I need to modify default port `8080` or may be pass custom profile for each `lxd-demo-server`? Any thoughts on how to setup/launch lxd-demo-server per user?  thanks.

**Comment by stgraber** [comment]
You can run multiple instances of it on different ports with different configuration I guess.

**Comment by Lakshmipathi** [comment]
okay thanks for the info. Let me try them
