### ISSUE TITLE
502 proxy error

### ISSUE THREAD

**Issue by diabolusss** [lxc/lxd-demo-server#23]
Hello. 
When i try to access https://linuxcontainers.org/lxd/try-it i receive this error:

> Proxy Error
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request
> 
> Reason: DNS lookup failure for: web-dl01.srv.dcmtl.stgraber.net
> 
> Apache/2.4.29 (Ubuntu) Server at linuxcontainers.org Port 443

**Comment by tomponline** [comment]
We are aware the site is down at the moment, @stgraber will be looking into it soon. Thanks.

**Comment by diabolusss** [comment]
Ok, thank you very much.
--
Ar laba vēlējumiem/ C наилучшими пожеланиями/ Best wishes,
Vitaly Hodiko


чт, 26 мар. 2020 г. в 13:47, TomP <notifications@github.com>:

**Comment by stgraber** [comment]
And back online, sorry about that.

**Comment by diabolusss** [comment]
Wow! That was fast! Thank you!
