### ISSUE TITLE
Getting errors while runing go build

### ISSUE THREAD

**Issue by DilipRenkila** [lxc/lxd-demo-server#3]
`$ go build`
 _/home/dilip/lxd-demo-server
./db.go:158: undefined: sqlite3 in sqlite3.ErrLocked
./db.go:158: undefined: sqlite3 in sqlite3.ErrBusy
 please can you explain me why this error happens?

**Comment by stgraber** [comment]
What OS are your trying to build this on?

**Comment by DilipRenkila** [comment]
ubuntu 16.04

**Comment by stgraber** [comment]
I'm unable to reproduce this, both a straight "go build" in the directory or a clean build from scratch with:

    mkdir /tmp/go
    export GOPATH=/tmp/go
    go get -v -x github.com/lxc/lxd-demo-server

Work fine here.

The error you're reporting would be consistent with you not having a built go-sqlite3 for some reason but I'm on 16.04 and it's all working fine here.

**Comment by DilipRenkila** [comment]
It works fine. 
`container: "my-base-container"
image: "my-image"`
Do i need to create an container and then substitute the container's name in the above ?

**Comment by stgraber** [comment]
Yep, or not set it and set the image instead. It's one or the other, pick what you prefer.
