### ISSUE TITLE
Errors in rest.go

### ISSUE THREAD

**Issue by markc** [lxc/lxd-demo-server#4]
I suspect this repo hasn't been updated for awhile...
```
~ go build
# _/home/u/localhost/var/www/lxd
./rest.go:175: not enough arguments in call to lxdDaemon.Init
./rest.go:458: not enough arguments in call to shared.ReaderToChannel
```

**Comment by stgraber** [comment]
I've been building it against the stable-2.0 LXD branch mostly which hasn't changed API recently.

But yeah, it should be updated for the current LXD API I guess.
