### ISSUE TITLE
remote mode simplestreams

### ISSUE THREAD

**Issue by mderouineau** [lxc/lxd-demo-server#8]
In some of your tutorials, you explain how to use an lxd server as an image server with the command lxc config set core.https_address "[::]:8443"

The lxd.go client used for the API does only accept servers using the simplestream protocol.
Is it possible to set lxd server in  simplestream for the remote mode ?

**Comment by stgraber** [comment]
This issue doesn't seem to have anything to do with lxd-demo-server which is the backend for https://linuxcontainers.org/lxd/try-it

LXD can pull images from other LXD servers using its internal protocol or from static HTTP servers over the simplestreams protocol (https + json files). LXD itself doesn't implement a simplestream server.

The Go client that's in github.com/lxc/lxd absolutely supports both LXD and simplestreams remote as that's what's used for the default command line client.
